/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliatedSchoolRouteImport } from './routes/affiliated-school'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigiLockerRouteImport } from './routes/digi-locker'
import { Route as DigilockerRouteImport } from './routes/digilocker'
import { Route as ExaminationRouteImport } from './routes/examination'
import { Route as HolidayListRouteImport } from './routes/holiday-list'
import { Route as RegionalCentreRouteImport } from './routes/regional-centre'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RtiRouteImport } from './routes/rti'
import { Route as SubjectCodeRouteImport } from './routes/subject-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatedSchoolRoute = AffiliatedSchoolRouteImport.update({
  id: '/affiliated-school',
  path: '/affiliated-school',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigiLockerRoute = DigiLockerRouteImport.update({
  id: '/digi-locker',
  path: '/digi-locker',
  getParentRoute: () => rootRouteImport,
} as any)
const DigilockerRoute = DigilockerRouteImport.update({
  id: '/digilocker',
  path: '/digilocker',
  getParentRoute: () => rootRouteImport,
} as any)
const ExaminationRoute = ExaminationRouteImport.update({
  id: '/examination',
  path: '/examination',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayListRoute = HolidayListRouteImport.update({
  id: '/holiday-list',
  path: '/holiday-list',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalCentreRoute = RegionalCentreRouteImport.update({
  id: '/regional-centre',
  path: '/regional-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RtiRoute = RtiRouteImport.update({
  id: '/rti',
  path: '/rti',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectCodeRoute = SubjectCodeRouteImport.update({
  id: '/subject-code',
  path: '/subject-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliated-school': typeof AffiliatedSchoolRoute
  '/contact': typeof ContactRoute
  '/digi-locker': typeof DigiLockerRoute
  '/digilocker': typeof DigilockerRoute
  '/examination': typeof ExaminationRoute
  '/holiday-list': typeof HolidayListRoute
  '/regional-centre': typeof RegionalCentreRoute
  '/result': typeof ResultRoute
  '/rti': typeof RtiRoute
  '/subject-code': typeof SubjectCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliated-school': typeof AffiliatedSchoolRoute
  '/contact': typeof ContactRoute
  '/digi-locker': typeof DigiLockerRoute
  '/digilocker': typeof DigilockerRoute
  '/examination': typeof ExaminationRoute
  '/holiday-list': typeof HolidayListRoute
  '/regional-centre': typeof RegionalCentreRoute
  '/result': typeof ResultRoute
  '/rti': typeof RtiRoute
  '/subject-code': typeof SubjectCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliated-school': typeof AffiliatedSchoolRoute
  '/contact': typeof ContactRoute
  '/digi-locker': typeof DigiLockerRoute
  '/digilocker': typeof DigilockerRoute
  '/examination': typeof ExaminationRoute
  '/holiday-list': typeof HolidayListRoute
  '/regional-centre': typeof RegionalCentreRoute
  '/result': typeof ResultRoute
  '/rti': typeof RtiRoute
  '/subject-code': typeof SubjectCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliated-school'
    | '/contact'
    | '/digi-locker'
    | '/digilocker'
    | '/examination'
    | '/holiday-list'
    | '/regional-centre'
    | '/result'
    | '/rti'
    | '/subject-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliated-school'
    | '/contact'
    | '/digi-locker'
    | '/digilocker'
    | '/examination'
    | '/holiday-list'
    | '/regional-centre'
    | '/result'
    | '/rti'
    | '/subject-code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliated-school'
    | '/contact'
    | '/digi-locker'
    | '/digilocker'
    | '/examination'
    | '/holiday-list'
    | '/regional-centre'
    | '/result'
    | '/rti'
    | '/subject-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AffiliatedSchoolRoute: typeof AffiliatedSchoolRoute
  ContactRoute: typeof ContactRoute
  DigiLockerRoute: typeof DigiLockerRoute
  DigilockerRoute: typeof DigilockerRoute
  ExaminationRoute: typeof ExaminationRoute
  HolidayListRoute: typeof HolidayListRoute
  RegionalCentreRoute: typeof RegionalCentreRoute
  ResultRoute: typeof ResultRoute
  RtiRoute: typeof RtiRoute
  SubjectCodeRoute: typeof SubjectCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliated-school': {
      id: '/affiliated-school'
      path: '/affiliated-school'
      fullPath: '/affiliated-school'
      preLoaderRoute: typeof AffiliatedSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digi-locker': {
      id: '/digi-locker'
      path: '/digi-locker'
      fullPath: '/digi-locker'
      preLoaderRoute: typeof DigiLockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digilocker': {
      id: '/digilocker'
      path: '/digilocker'
      fullPath: '/digilocker'
      preLoaderRoute: typeof DigilockerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examination': {
      id: '/examination'
      path: '/examination'
      fullPath: '/examination'
      preLoaderRoute: typeof ExaminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-list': {
      id: '/holiday-list'
      path: '/holiday-list'
      fullPath: '/holiday-list'
      preLoaderRoute: typeof HolidayListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-centre': {
      id: '/regional-centre'
      path: '/regional-centre'
      fullPath: '/regional-centre'
      preLoaderRoute: typeof RegionalCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rti': {
      id: '/rti'
      path: '/rti'
      fullPath: '/rti'
      preLoaderRoute: typeof RtiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject-code': {
      id: '/subject-code'
      path: '/subject-code'
      fullPath: '/subject-code'
      preLoaderRoute: typeof SubjectCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AffiliatedSchoolRoute: AffiliatedSchoolRoute,
  ContactRoute: ContactRoute,
  DigiLockerRoute: DigiLockerRoute,
  DigilockerRoute: DigilockerRoute,
  ExaminationRoute: ExaminationRoute,
  HolidayListRoute: HolidayListRoute,
  RegionalCentreRoute: RegionalCentreRoute,
  ResultRoute: ResultRoute,
  RtiRoute: RtiRoute,
  SubjectCodeRoute: SubjectCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
